# Generated by Django 6.0.3 on 2026-05-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_userprofile_delete_healthdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
