# Generated by Django 6.0.3 on 2026-05-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_registeruser_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='email_verification_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='email_verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
