# Generated by Django 6.0.5 on 2026-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_registeruser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='email_verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
