# Generated by Django 6.0.5 on 2026-05-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_registeruser_email_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_scores', to='hello.registeruser')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
    ]
